
class Emoji:
    ada = '₳'
    lightning = '⚡'
    fire = '🔥'
    moneyBag = '💰'
    pickaxe = '⛏'
    swords = '⚔'
    throphy = '🏆'
    annoyed = '😤'
    warning = '⚠'
    alert = '‼'
    like = '👍'
    link = '🔗'
    globe = '🌐'
    tools = '🛠'
    chains = '⛓'
    brick = '🧱'
    meat = '🥩'
    flyingMoney = '💸'
    clock = '⏱'
    arrowDown = '🔻'
    arrowUp = '🔺'
    star = '⭐'
    dice = '🎲'
    crown = '👑'
    party = '🥳'